AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DomainName:
    Type: String
    Description: Domain name for the application
Resources:
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e8283d57-9b41-45a4-aac7-422091c75a02
  MyPublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: us-east-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: MyPublicSubnet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4768cd83-8d59-4613-8fa5-37f65b22a83b
  MyPrivateSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-1b
      Tags:
        - Key: Name
          Value: MyPrivateSubnet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1b2a4eba-6d96-4a59-8273-c530ea2ef543
  MyNatGateway:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: !GetAtt MyEIP.AllocationId
      SubnetId: !Ref MyPublicSubnet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 88188133-f5c1-4d91-9df8-30a2246b5b42
  MyEIP:
    Type: 'AWS::EC2::EIP'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 68dc0ab3-d9c3-4a1b-a93e-5813c4606afd
  MyRoute53HostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      Name: !Ref DomainName
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ac729c96-465b-42cc-b76f-0ab1a06dc3a3
    DependsOn:
      - MyWAFWebACL
  MyWAFWebACL:
    Type: 'AWS::WAF::WebACL'
    Properties:
      DefaultAction:
        Type: ALLOW
      MetricName: MyWAFWebACLMetric
      Name: MyWAFWebACL
      Rules: []
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b57740e1-c198-4672-a582-b0cf64707b6f
  MyCloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt MyS3Bucket.DomainName
            Id: MyS3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: MyS3Origin
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        Aliases:
          - !Ref DomainName
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref MyACMCertificate
          SslSupportMethod: sni-only
        WebACLId: !Ref MyWAFWebACL
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 6b2b4e41-898b-4a6b-98d1-87147533da24
  MyACMCertificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ffa0b0e9-b753-4c47-8851-b4a931e85f07
  MyALB:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Subnets:
        - !Ref MyPublicSubnet
      SecurityGroups:
        - sg-0123456789abcdef0
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
      Scheme: internet-facing
      Tags:
        - Key: Name
          Value: MyALB
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 8172786e-b1c0-4dbf-8bca-1877da233bc4
  MyListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: text/plain
            StatusCode: 200
            Content: OK
      LoadBalancerArn: !Ref MyALB
      Port: 80
      Protocol: HTTP
    Metadata:
      'AWS::CloudFormation::Designer':
        id: d153c391-e948-4dab-afec-0ac1c99007e9
  MyTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 5
      Matcher:
        HttpCode: '200'
      Name: MyTargetGroup
      Port: 80
      Protocol: HTTP
      TargetType: instance
      UnhealthyThresholdCount: 2
      VpcId: !Ref MyVPC
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 10a51a51-4238-4ae8-a967-33e5e1a1142c
  MyALBListenerRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup
      Conditions:
        - Field: path-pattern
          Values:
            - /*
      ListenerArn: !Ref MyListener
      Priority: 1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 89dce425-e9eb-41b1-a3c6-34a7bc983026
  MyRDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 20
      DBInstanceIdentifier: MyRDSInstance
      DBInstanceClass: db.t2.micro
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: admin
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 43ac413e-c47f-48a6-859a-91b19123c47d
Metadata:
  'AWS::CloudFormation::Designer':
    43ac413e-c47f-48a6-859a-91b19123c47d:
      size:
        width: 60
        height: 60
      position:
        x: 480
        'y': 90
      z: 1
      embeds: []
    ffa0b0e9-b753-4c47-8851-b4a931e85f07:
      size:
        width: 60
        height: 60
      position:
        x: 480
        'y': 210
      z: 1
      embeds: []
    b57740e1-c198-4672-a582-b0cf64707b6f:
      size:
        width: 60
        height: 60
      position:
        x: 480
        'y': 330
      z: 1
      embeds: []
    6b2b4e41-898b-4a6b-98d1-87147533da24:
      size:
        width: 60
        height: 60
      position:
        x: 480
        'y': 450
      z: 1
      embeds: []
    ac729c96-465b-42cc-b76f-0ab1a06dc3a3:
      size:
        width: 150
        height: 150
      position:
        x: 270
        'y': 300
      z: 1
      embeds: []
      dependson:
        - b57740e1-c198-4672-a582-b0cf64707b6f
    68dc0ab3-d9c3-4a1b-a93e-5813c4606afd:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 510
      z: 1
      embeds: []
    e8283d57-9b41-45a4-aac7-422091c75a02:
      size:
        width: 150
        height: 150
      position:
        x: 60
        'y': 300
      z: 1
      embeds: []
    10a51a51-4238-4ae8-a967-33e5e1a1142c:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 510
      z: 1
      embeds: []
    1b2a4eba-6d96-4a59-8273-c530ea2ef543:
      size:
        width: 150
        height: 150
      position:
        x: 270
        'y': 90
      z: 1
      embeds: []
    4768cd83-8d59-4613-8fa5-37f65b22a83b:
      size:
        width: 150
        height: 150
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    8172786e-b1c0-4dbf-8bca-1877da233bc4:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 510
      z: 1
      embeds: []
    d153c391-e948-4dab-afec-0ac1c99007e9:
      size:
        width: 60
        height: 60
      position:
        x: 420
        'y': 570
      z: 1
      embeds: []
    89dce425-e9eb-41b1-a3c6-34a7bc983026:
      size:
        width: 60
        height: 60
      position:
        x: 540
        'y': 570
      z: 1
      embeds: []
    88188133-f5c1-4d91-9df8-30a2246b5b42:
      size:
        width: 60
        height: 60
      position:
        x: 600
        'y': 90
      z: 1
      embeds: []
    bec6ff6e-763b-4f7d-8a3d-65f3918aaae6:
      source:
        id: ac729c96-465b-42cc-b76f-0ab1a06dc3a3
      target:
        id: b57740e1-c198-4672-a582-b0cf64707b6f
      z: 11


